[project]
name = "matchms-version-comparison"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Marco Visani", email = "92217074+mvisani@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "click>=8.5.0",
    "downloaders>=1.0.22",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
]

[project.scripts]
matchms-version-comparison = "matchms_version_comparison:main"

[build-system]
requires = ["uv_build>=0.12.14,<0.13.0"]
build-backend = "uv_build"
